name: Prettier code formatter

on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main

jobs:
  check:
    # available images: https://github.com/actions/runner-images#available-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
      - name: Install dependencies 💾
        run: npm ci
      - name: Prettier Check 🔎
        id: prettier
        run: npx prettier . --check
      - name: Create diff 📝
        # https://docs.github.com/en/actions/learn-github-actions/expressions#failure
        if: ${{ failure() }}
        run: |
          npx prettier . --write
          git diff > diff.txt
          # exit with error if diff is not empty
          if [ -s diff.txt ]; then
            echo "Code style issues found. Please run 'npm run format' and commit the changes."
            exit 1
          fi
      - name: Upload html diff ⬆️
        # https://docs.github.com/en/actions/learn-github-actions/expressions#failure
        if: ${{ failure() && steps.prettier.conclusion == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: prettier-diff
          path: diff.html
      - name: Dispatch information to repository 🗣️
        if: ${{ failure() && steps.prettier.conclusion == 'failure' && github.event_name == 'pull_request' }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          event-type: prettier-failed-on-pr
          client-payload: '{{ "pr_number": ${{ github.event.pull_request.number }}, "run_id": ${{ github.run_id }}, "artifact_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload.outputs.artifact-id }}" }}'
